/**
 ******************************************************************************
 * @file           : pmu_adc.c
 * @brief          : Universal ADC Input Driver Implementation
 * @author         : R2 m-sport
 * @date           : 2025-12-21
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 R2 m-sport.
 * All rights reserved.
 *
 * 20 Universal Analog/Digital Inputs Implementation:
 * - Switch Active Low: Digital input with active low logic
 * - Switch Active High: Digital input with active high logic
 * - Rotary Switch: Multi-position switch with voltage divider
 * - Linear Analog: Linear voltage input (0-5V or 0-10V)
 * - Calibrated Analog: Analog input with custom calibration curve
 * - Frequency Input: Digital frequency measurement (RPM, speed, etc.)
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "pmu_adc.h"
#include "stm32h7xx_hal.h"
#include <string.h>

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/
#define ADC_DMA_BUFFER_SIZE     20          /* 20 channels */
#define FREQUENCY_SAMPLE_TIME_MS 1000       /* 1 second for frequency measurement */

/* Private macro -------------------------------------------------------------*/
#define IS_VALID_INPUT(ch)      ((ch) < PMU30_NUM_ADC_INPUTS)
#define VOLTAGE_FROM_ADC(adc)   (((adc) * PMU_ADC_VREF_MV) / PMU_ADC_RESOLUTION)

/* Private variables ---------------------------------------------------------*/
static PMU_ADC_Input_t inputs[PMU30_NUM_ADC_INPUTS];
static PMU_InputConfig_t* input_configs[PMU30_NUM_ADC_INPUTS];
static uint16_t adc_dma_buffer[ADC_DMA_BUFFER_SIZE];
static ADC_HandleTypeDef* hadc_inputs;

#ifndef UNIT_TEST
/* ADC Handles - typically defined in main.c or generated by STM32CubeMX */
static ADC_HandleTypeDef hadc1;
static ADC_HandleTypeDef hadc2;
static ADC_HandleTypeDef hadc3;
#endif

/* Private function prototypes -----------------------------------------------*/
static void ADC_ProcessSwitchActiveLow(uint8_t channel);
static void ADC_ProcessSwitchActiveHigh(uint8_t channel);
static void ADC_ProcessRotarySwitch(uint8_t channel);
static void ADC_ProcessLinearAnalog(uint8_t channel);
static void ADC_ProcessCalibratedAnalog(uint8_t channel);
static void ADC_ProcessFrequencyInput(uint8_t channel);
static uint16_t ADC_ApplyFilter(uint8_t channel, uint16_t new_value);
static float ADC_ApplyCalibration(PMU_InputConfig_t* config, uint16_t raw);
static uint16_t ADC_ReadChannel(uint8_t channel);

/* Exported functions --------------------------------------------------------*/

/**
 * @brief Initialize ADC driver
 * @retval HAL status
 */
HAL_StatusTypeDef PMU_ADC_Init(void)
{
    HAL_StatusTypeDef status = HAL_OK;

    /* Clear all data */
    memset(inputs, 0, sizeof(inputs));
    memset(input_configs, 0, sizeof(input_configs));
    memset(adc_dma_buffer, 0, sizeof(adc_dma_buffer));

    /* Initialize all inputs */
    for (uint8_t i = 0; i < PMU30_NUM_ADC_INPUTS; i++) {
        inputs[i].raw_value = 0;
        inputs[i].scaled_value = 0.0f;
        inputs[i].digital_state = 0;
        inputs[i].frequency_hz = 0;
        inputs[i].debounce_counter = 0;
        inputs[i].filter_index = 0;
        inputs[i].last_edge_time = 0;
        inputs[i].edge_count = 0;
    }

    /* Initialize ADC peripheral for analog inputs
     * STM32H743: 3× ADC @ 3.6 MSPS (16-bit resolution)
     * 20 channels distributed across ADC1/2/3 for optimal sampling
     */

#ifndef UNIT_TEST
    /* ADC1 Configuration (Channels 0-7) */
    hadc_inputs = &hadc1;

    ADC_ChannelConfTypeDef sConfig = {0};

    /* Configure ADC1 common settings */
    hadc1.Instance = ADC1;
    hadc1.Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV2;
    hadc1.Init.Resolution = ADC_RESOLUTION_12B;  /* 12-bit for speed */
    hadc1.Init.ScanConvMode = ADC_SCAN_ENABLE;   /* Scan multiple channels */
    hadc1.Init.EOCSelection = ADC_EOC_SEQ_CONV;
    hadc1.Init.LowPowerAutoWait = DISABLE;
    hadc1.Init.ContinuousConvMode = ENABLE;      /* Continuous conversion */
    hadc1.Init.NbrOfConversion = 8;              /* 8 channels on ADC1 */
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConv = ADC_SOFTWARE_START;
    hadc1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.ConversionDataManagement = ADC_CONVERSIONDATA_DMA_CIRCULAR;
    hadc1.Init.Overrun = ADC_OVR_DATA_OVERWRITTEN;
    hadc1.Init.LeftBitShift = ADC_LEFTBITSHIFT_NONE;
    hadc1.Init.OversamplingMode = DISABLE;

    if (HAL_ADC_Init(&hadc1) != HAL_OK) {
        return HAL_ERROR;
    }

    /* Configure ADC channels - Pin mapping to be defined in MX_GPIO_Init()
     * Channel mapping (example - adjust based on actual hardware):
     * ADC1_IN0  (PA0)  - Input 0
     * ADC1_IN1  (PA1)  - Input 1
     * ADC1_IN2  (PA2)  - Input 2
     * ADC1_IN3  (PA3)  - Input 3
     * ADC1_IN4  (PA4)  - Input 4
     * ADC1_IN5  (PA5)  - Input 5
     * ADC1_IN6  (PA6)  - Input 6
     * ADC1_IN7  (PA7)  - Input 7
     */

    for (uint8_t ch = 0; ch < 8; ch++) {
        sConfig.Channel = ADC_CHANNEL_0 + ch;
        sConfig.Rank = ADC_REGULAR_RANK_1 + ch;
        sConfig.SamplingTime = ADC_SAMPLETIME_64CYCLES_5;
        sConfig.SingleDiff = ADC_SINGLE_ENDED;
        sConfig.OffsetNumber = ADC_OFFSET_NONE;
        sConfig.Offset = 0;

        if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK) {
            return HAL_ERROR;
        }
    }

    /* Start ADC1 DMA */
    if (HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_dma_buffer, 8) != HAL_OK) {
        return HAL_ERROR;
    }

    /* ========================================================================
     * ADC2 Configuration (Channels 8-13, 6 inputs)
     * Pin mapping:
     * ADC2_IN0  (PA0_C) - Input 8
     * ADC2_IN1  (PA1_C) - Input 9
     * ADC2_IN10 (PC0)   - Input 10
     * ADC2_IN11 (PC1)   - Input 11
     * ADC2_IN12 (PC2)   - Input 12
     * ADC2_IN13 (PC3)   - Input 13
     * ======================================================================== */
    hadc2.Instance = ADC2;
    hadc2.Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV2;
    hadc2.Init.Resolution = ADC_RESOLUTION_12B;
    hadc2.Init.ScanConvMode = ADC_SCAN_ENABLE;
    hadc2.Init.EOCSelection = ADC_EOC_SEQ_CONV;
    hadc2.Init.LowPowerAutoWait = DISABLE;
    hadc2.Init.ContinuousConvMode = ENABLE;
    hadc2.Init.NbrOfConversion = 6;              /* 6 channels on ADC2 */
    hadc2.Init.DiscontinuousConvMode = DISABLE;
    hadc2.Init.ExternalTrigConv = ADC_SOFTWARE_START;
    hadc2.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc2.Init.ConversionDataManagement = ADC_CONVERSIONDATA_DMA_CIRCULAR;
    hadc2.Init.Overrun = ADC_OVR_DATA_OVERWRITTEN;
    hadc2.Init.LeftBitShift = ADC_LEFTBITSHIFT_NONE;
    hadc2.Init.OversamplingMode = DISABLE;

    if (HAL_ADC_Init(&hadc2) != HAL_OK) {
        return HAL_ERROR;
    }

    /* Configure ADC2 channels */
    const uint32_t adc2_channels[6] = {
        ADC_CHANNEL_0, ADC_CHANNEL_1, ADC_CHANNEL_10,
        ADC_CHANNEL_11, ADC_CHANNEL_12, ADC_CHANNEL_13
    };

    for (uint8_t i = 0; i < 6; i++) {
        sConfig.Channel = adc2_channels[i];
        sConfig.Rank = ADC_REGULAR_RANK_1 + i;
        sConfig.SamplingTime = ADC_SAMPLETIME_64CYCLES_5;
        sConfig.SingleDiff = ADC_SINGLE_ENDED;
        sConfig.OffsetNumber = ADC_OFFSET_NONE;
        sConfig.Offset = 0;

        if (HAL_ADC_ConfigChannel(&hadc2, &sConfig) != HAL_OK) {
            return HAL_ERROR;
        }
    }

    /* Start ADC2 DMA */
    if (HAL_ADC_Start_DMA(&hadc2, (uint32_t*)&adc_dma_buffer[8], 6) != HAL_OK) {
        return HAL_ERROR;
    }

    /* ========================================================================
     * ADC3 Configuration (Channels 14-19, 6 inputs)
     * Pin mapping:
     * ADC3_IN0  (PC2_C) - Input 14
     * ADC3_IN1  (PC3_C) - Input 15
     * ADC3_IN10 (PC0)   - Input 16 (shared with ADC2, use alternate)
     * ADC3_IN11 (PC1)   - Input 17
     * ADC3_IN12 (PH2)   - Input 18
     * ADC3_IN13 (PH3)   - Input 19
     * ======================================================================== */
    hadc3.Instance = ADC3;
    hadc3.Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV2;
    hadc3.Init.Resolution = ADC_RESOLUTION_12B;
    hadc3.Init.ScanConvMode = ADC_SCAN_ENABLE;
    hadc3.Init.EOCSelection = ADC_EOC_SEQ_CONV;
    hadc3.Init.LowPowerAutoWait = DISABLE;
    hadc3.Init.ContinuousConvMode = ENABLE;
    hadc3.Init.NbrOfConversion = 6;              /* 6 channels on ADC3 */
    hadc3.Init.DiscontinuousConvMode = DISABLE;
    hadc3.Init.ExternalTrigConv = ADC_SOFTWARE_START;
    hadc3.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc3.Init.ConversionDataManagement = ADC_CONVERSIONDATA_DMA_CIRCULAR;
    hadc3.Init.Overrun = ADC_OVR_DATA_OVERWRITTEN;
    hadc3.Init.LeftBitShift = ADC_LEFTBITSHIFT_NONE;
    hadc3.Init.OversamplingMode = DISABLE;

    if (HAL_ADC_Init(&hadc3) != HAL_OK) {
        return HAL_ERROR;
    }

    /* Configure ADC3 channels */
    const uint32_t adc3_channels[6] = {
        ADC_CHANNEL_0, ADC_CHANNEL_1, ADC_CHANNEL_10,
        ADC_CHANNEL_11, ADC_CHANNEL_12, ADC_CHANNEL_13
    };

    for (uint8_t i = 0; i < 6; i++) {
        sConfig.Channel = adc3_channels[i];
        sConfig.Rank = ADC_REGULAR_RANK_1 + i;
        sConfig.SamplingTime = ADC_SAMPLETIME_64CYCLES_5;
        sConfig.SingleDiff = ADC_SINGLE_ENDED;
        sConfig.OffsetNumber = ADC_OFFSET_NONE;
        sConfig.Offset = 0;

        if (HAL_ADC_ConfigChannel(&hadc3, &sConfig) != HAL_OK) {
            return HAL_ERROR;
        }
    }

    /* Start ADC3 DMA */
    if (HAL_ADC_Start_DMA(&hadc3, (uint32_t*)&adc_dma_buffer[14], 6) != HAL_OK) {
        return HAL_ERROR;
    }

    /* ========================================================================
     * Frequency Input Configuration (GPIO EXTI)
     * 4 frequency inputs on PB0-PB3
     * Used for RPM, speed sensors, etc.
     * ======================================================================== */
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOB clock */
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* Configure PB0-PB3 as input with pull-up, EXTI interrupt */
    GPIO_InitStruct.Pin = GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* Enable EXTI interrupts */
    HAL_NVIC_SetPriority(EXTI0_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(EXTI0_IRQn);
    HAL_NVIC_SetPriority(EXTI1_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(EXTI1_IRQn);
    HAL_NVIC_SetPriority(EXTI2_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(EXTI2_IRQn);
    HAL_NVIC_SetPriority(EXTI3_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(EXTI3_IRQn);

#endif /* UNIT_TEST */

    return status;
}

/**
 * @brief Update all ADC inputs - call at 1kHz
 * @retval None
 */
void PMU_ADC_Update(void)
{
    /* Read all ADC channels (would be automatic with DMA) */
    for (uint8_t i = 0; i < PMU30_NUM_ADC_INPUTS; i++) {
        /* Read and filter raw ADC value */
        uint16_t raw = ADC_ReadChannel(i);
        inputs[i].raw_value = ADC_ApplyFilter(i, raw);

        /* Process based on configured input type */
        if (input_configs[i] != NULL) {
            switch (input_configs[i]->type) {
                case PMU_INPUT_SWITCH_ACTIVE_LOW:
                    ADC_ProcessSwitchActiveLow(i);
                    break;

                case PMU_INPUT_SWITCH_ACTIVE_HIGH:
                    ADC_ProcessSwitchActiveHigh(i);
                    break;

                case PMU_INPUT_ROTARY_SWITCH:
                    ADC_ProcessRotarySwitch(i);
                    break;

                case PMU_INPUT_LINEAR_ANALOG:
                    ADC_ProcessLinearAnalog(i);
                    break;

                case PMU_INPUT_CALIBRATED_ANALOG:
                    ADC_ProcessCalibratedAnalog(i);
                    break;

                case PMU_INPUT_FREQUENCY:
                    ADC_ProcessFrequencyInput(i);
                    break;

                default:
                    /* Unknown type - treat as raw analog */
                    inputs[i].scaled_value = VOLTAGE_FROM_ADC(inputs[i].raw_value) / 1000.0f;
                    break;
            }
        }
    }
}

/**
 * @brief Get raw ADC value
 * @param channel Input channel (0-19)
 * @retval Raw ADC value (0-1023)
 */
uint16_t PMU_ADC_GetRawValue(uint8_t channel)
{
    if (!IS_VALID_INPUT(channel)) {
        return 0;
    }
    return inputs[channel].raw_value;
}

/**
 * @brief Get scaled value with calibration applied
 * @param channel Input channel (0-19)
 * @retval Scaled value in configured units
 */
float PMU_ADC_GetScaledValue(uint8_t channel)
{
    if (!IS_VALID_INPUT(channel)) {
        return 0.0f;
    }
    return inputs[channel].scaled_value;
}

/**
 * @brief Get digital state (for switch inputs)
 * @param channel Input channel (0-19)
 * @retval Digital state (0 or 1)
 */
uint8_t PMU_ADC_GetDigitalState(uint8_t channel)
{
    if (!IS_VALID_INPUT(channel)) {
        return 0;
    }
    return inputs[channel].digital_state;
}

/**
 * @brief Get frequency (for frequency inputs)
 * @param channel Input channel (0-19)
 * @retval Frequency in Hz
 */
uint32_t PMU_ADC_GetFrequency(uint8_t channel)
{
    if (!IS_VALID_INPUT(channel)) {
        return 0;
    }
    return inputs[channel].frequency_hz;
}

/**
 * @brief Get input runtime data
 * @param channel Input channel (0-19)
 * @retval Pointer to input data
 */
PMU_ADC_Input_t* PMU_ADC_GetInputData(uint8_t channel)
{
    if (!IS_VALID_INPUT(channel)) {
        return NULL;
    }
    return &inputs[channel];
}

/**
 * @brief Set input configuration
 * @param channel Input channel (0-19)
 * @param config Pointer to configuration
 * @retval HAL status
 */
HAL_StatusTypeDef PMU_ADC_SetConfig(uint8_t channel, PMU_InputConfig_t* config)
{
    if (!IS_VALID_INPUT(channel) || config == NULL) {
        return HAL_ERROR;
    }

    input_configs[channel] = config;

    /* Clear filter buffer when config changes */
    memset(inputs[channel].filter_buffer, 0, sizeof(inputs[channel].filter_buffer));
    inputs[channel].filter_index = 0;

    return HAL_OK;
}

/* Private functions ---------------------------------------------------------*/

/**
 * @brief Process Switch Active Low input
 * @param channel Input channel
 * @retval None
 */
static void ADC_ProcessSwitchActiveLow(uint8_t channel)
{
    PMU_InputConfig_t* cfg = input_configs[channel];
    uint16_t voltage_mv = VOLTAGE_FROM_ADC(inputs[channel].raw_value);

    /* Active low: LOW = pressed (1), HIGH = released (0) */
    uint8_t new_state = (voltage_mv < cfg->threshold_low_mv) ? 1 : 0;

    /* Debouncing */
    if (new_state != inputs[channel].digital_state) {
        inputs[channel].debounce_counter++;
        if (inputs[channel].debounce_counter >= cfg->debounce_ms) {
            inputs[channel].digital_state = new_state;
            inputs[channel].debounce_counter = 0;
        }
    } else {
        inputs[channel].debounce_counter = 0;
    }

    inputs[channel].scaled_value = (float)inputs[channel].digital_state;
}

/**
 * @brief Process Switch Active High input
 * @param channel Input channel
 * @retval None
 */
static void ADC_ProcessSwitchActiveHigh(uint8_t channel)
{
    PMU_InputConfig_t* cfg = input_configs[channel];
    uint16_t voltage_mv = VOLTAGE_FROM_ADC(inputs[channel].raw_value);

    /* Active high: HIGH = pressed (1), LOW = released (0) */
    uint8_t new_state = (voltage_mv > cfg->threshold_high_mv) ? 1 : 0;

    /* Debouncing */
    if (new_state != inputs[channel].digital_state) {
        inputs[channel].debounce_counter++;
        if (inputs[channel].debounce_counter >= cfg->debounce_ms) {
            inputs[channel].digital_state = new_state;
            inputs[channel].debounce_counter = 0;
        }
    } else {
        inputs[channel].debounce_counter = 0;
    }

    inputs[channel].scaled_value = (float)inputs[channel].digital_state;
}

/**
 * @brief Process Rotary Switch input (multi-position with voltage divider)
 * @param channel Input channel
 * @retval None
 */
static void ADC_ProcessRotarySwitch(uint8_t channel)
{
    PMU_InputConfig_t* cfg = input_configs[channel];
    uint16_t voltage_mv = VOLTAGE_FROM_ADC(inputs[channel].raw_value);

    /* Determine switch position based on voltage ranges
     * Example for 8-position switch:
     * Pos 0: 0.00V, Pos 1: 0.71V, Pos 2: 1.43V, Pos 3: 2.14V
     * Pos 4: 2.86V, Pos 5: 3.57V, Pos 6: 4.29V, Pos 7: 5.00V
     */

    /* Calculate position (0-7 for 8-position switch) */
    uint8_t position = 0;
    uint16_t step_mv = 5000 / 8; /* Assuming 8 positions and 5V range */

    for (uint8_t i = 0; i < 8; i++) {
        uint16_t pos_voltage = i * step_mv;
        if (voltage_mv < (pos_voltage + step_mv / 2)) {
            position = i;
            break;
        }
    }

    inputs[channel].digital_state = position;
    inputs[channel].scaled_value = (float)position;
}

/**
 * @brief Process Linear Analog input
 * @param channel Input channel
 * @retval None
 */
static void ADC_ProcessLinearAnalog(uint8_t channel)
{
    PMU_InputConfig_t* cfg = input_configs[channel];

    /* Apply linear scaling: Result = (Raw × Multiplier / Divider) + Offset */
    float voltage_v = VOLTAGE_FROM_ADC(inputs[channel].raw_value) / 1000.0f;
    inputs[channel].scaled_value = (voltage_v * cfg->multiplier) + cfg->offset;
}

/**
 * @brief Process Calibrated Analog input with custom curve
 * @param channel Input channel
 * @retval None
 */
static void ADC_ProcessCalibratedAnalog(uint8_t channel)
{
    PMU_InputConfig_t* cfg = input_configs[channel];

    /* Apply calibration curve if available */
    inputs[channel].scaled_value = ADC_ApplyCalibration(cfg, inputs[channel].raw_value);
}

/**
 * @brief Process Frequency Input (for RPM, speed sensors, etc.)
 * @param channel Input channel
 * @retval None
 */
static void ADC_ProcessFrequencyInput(uint8_t channel)
{
    /* Frequency measurement using edge counting
     * This would typically use an external interrupt or timer input capture
     * For now, calculate based on edge count over sample period
     */

    static uint32_t last_freq_update[PMU30_NUM_ADC_INPUTS] = {0};
    uint32_t current_time = HAL_GetTick();

    /* Update frequency every second */
    if ((current_time - last_freq_update[channel]) >= FREQUENCY_SAMPLE_TIME_MS) {
        /* Calculate frequency from edge count */
        inputs[channel].frequency_hz = inputs[channel].edge_count;
        inputs[channel].edge_count = 0;
        last_freq_update[channel] = current_time;
    }

    /* Apply multiplier for RPM calculation (e.g., pulses per revolution) */
    PMU_InputConfig_t* cfg = input_configs[channel];
    if (cfg != NULL) {
        inputs[channel].scaled_value = inputs[channel].frequency_hz * cfg->multiplier;
    } else {
        inputs[channel].scaled_value = (float)inputs[channel].frequency_hz;
    }
}

/**
 * @brief Apply moving average filter
 * @param channel Input channel
 * @param new_value New raw value
 * @retval Filtered value
 */
static uint16_t ADC_ApplyFilter(uint8_t channel, uint16_t new_value)
{
    /* Get filter size from config, default to 4 samples */
    uint8_t filter_size = 4;
    if (input_configs[channel] != NULL && input_configs[channel]->filter_samples > 0) {
        filter_size = input_configs[channel]->filter_samples;
        if (filter_size > 8) filter_size = 8;
    }

    /* Add to circular buffer */
    inputs[channel].filter_buffer[inputs[channel].filter_index] = new_value;
    inputs[channel].filter_index = (inputs[channel].filter_index + 1) % filter_size;

    /* Calculate average */
    uint32_t sum = 0;
    for (uint8_t i = 0; i < filter_size; i++) {
        sum += inputs[channel].filter_buffer[i];
    }

    return (uint16_t)(sum / filter_size);
}

/**
 * @brief Apply calibration curve to raw value
 * @param config Input configuration
 * @param raw Raw ADC value
 * @retval Calibrated value
 */
static float ADC_ApplyCalibration(PMU_InputConfig_t* config, uint16_t raw)
{
    /* For now, use simple linear calibration
     * In full implementation, this could use lookup table with interpolation
     * for non-linear sensors (temp sensors, pressure sensors, etc.)
     */

    float voltage_v = VOLTAGE_FROM_ADC(raw) / 1000.0f;
    return (voltage_v * config->multiplier) + config->offset;
}

/**
 * @brief Read ADC channel value
 * @param channel Input channel
 * @retval Raw ADC value (0-1023)
 */
static uint16_t ADC_ReadChannel(uint8_t channel)
{
    /* With DMA in circular mode, ADC values are automatically updated
     * in adc_dma_buffer by hardware. Just read the value directly.
     *
     * Channel mapping:
     * 0-7:   ADC1 channels (adc_dma_buffer[0-7])
     * 8-13:  ADC2 channels (would be in separate buffer)
     * 14-19: ADC3 channels (would be in separate buffer)
     */

    if (channel < ADC_DMA_BUFFER_SIZE) {
        /* STM32H7 ADC is 16-bit, but we configured it for 12-bit
         * Scale to 10-bit for consistency with PMU_ADC_RESOLUTION (1024)
         */
        return adc_dma_buffer[channel] >> 2;  /* 12-bit to 10-bit */
    }

#ifdef UNIT_TEST
    /* For unit tests, return mid-scale dummy value */
    return 512;
#else
    /* Out of range channel */
    return 0;
#endif
}

/**
 * @brief EXTI callback for frequency input edge detection
 * @param GPIO_Pin Pin number
 * @retval None
 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    /* Determine which input channel triggered the interrupt */
    for (uint8_t i = 0; i < PMU30_NUM_ADC_INPUTS; i++) {
        if (input_configs[i] != NULL &&
            input_configs[i]->type == PMU_INPUT_FREQUENCY) {

            /* Increment edge counter */
            inputs[i].edge_count++;
            inputs[i].last_edge_time = HAL_GetTick();
            break;
        }
    }
}

/************************ (C) COPYRIGHT R2 m-sport *****END OF FILE****/
